### PR TITLE
Transition the user from the addEventScreen bug

### LINKED ISSUE #95: Transition from creating an event bug

### PR DESCRIPTION
**Pull request by plazluis**
This change will prevent the user from restarting the app to view the updated events on the home screen after creating one

### CODE REVIEW

File: app/src/main/java/com/example/giftly/AddEventScreen.java [hunk 1]
```diff
@@ -109,7 +109,7 @@ public void onClick(View view) {
                             @Override
                             public void onSuccess(String eventID) {
                                 Log.d(TAG, "Successfully Created Event");
-                                Intent intent = new Intent(AddEventScreen.this, DisplayEventScreen.class);
```
Comment (itsaruon) [inline app/src/main/java/com/example/giftly/AddEventScreen.java:112]: Possibly revise the code to ensure that the correct Intent is used for each case

**Review by itsaruon — COMMENTED** [review]
Possibly revise the code to ensure that the correct Intent is used for each case

**Review by itsaruon — APPROVED** [review]
Possibly revise the code to ensure that the correct Intent is used for each case
